jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls -la
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install build
      - run: python -m build   # <-- MUST BE RUN FROM THE ROOT
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

