jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install build
      - run: python -m build    # <-- THIS should run in project root, NOT matrixswarm/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

